import {Post} from './Post';

export const MOCK_USERS = [
  {id: 'u1', name: '张伟', avatar: 'https://i.pravatar.cc/150?img=1'},
  {id: 'u2', name: '李娜', avatar: 'https://i.pravatar.cc/150?img=2'},
  {id: 'u3', name: '王芳', avatar: 'https://i.pravatar.cc/150?img=3'},
  {id: 'u4', name: '刘洋', avatar: 'https://i.pravatar.cc/150?img=4'},
  {id: 'u5', name: '陈静', avatar: 'https://i.pravatar.cc/150?img=5'},
  {id: 'u6', name: '杨帆', avatar: 'https://i.pravatar.cc/150?img=6'},
  {id: 'me', name: '我', avatar: 'https://i.pravatar.cc/150?img=10'},
];

const PHOTOS = [
  'https://picsum.photos/seed/a/400/400',
  'https://picsum.photos/seed/b/400/400',
  'https://picsum.photos/seed/c/400/400',
  'https://picsum.photos/seed/d/400/400',
  'https://picsum.photos/seed/e/400/400',
  'https://picsum.photos/seed/f/400/400',
  'https://picsum.photos/seed/g/400/400',
  'https://picsum.photos/seed/h/400/400',
  'https://picsum.photos/seed/i/400/400',
];

export const mockPosts: Post[] = [
  {id: 'p1', user: MOCK_USERS[0], type: 'image', content: '周末出游，风景真不错！', images: [PHOTOS[0]], location: '西湖风景区',
    likes: [MOCK_USERS[1], MOCK_USERS[2]],
    comments: [
      {id: 'c1', userId: 'u2', userName: '李娜', content: '好漂亮！'},
      {id: 'c2', userId: 'u3', userName: '王芳', content: '在哪里拍的？'},
      {id: 'c3', userId: 'u1', userName: '张伟', content: '西湖边～', replyTo: {userId: 'u3', userName: '王芳'}},
    ], createdAt: Date.now() - 1000 * 60 * 5},
  {id: 'p2', user: MOCK_USERS[1], type: 'text',
    content: '今天读完了《人类简史》，感触颇深。书中提到智人之所以能统治地球，是因为我们能相信"虚构故事"——货币、国家、宗教都是人类共同的想象。这种能力让我们能大规模协作，而其他动物无法做到。推荐每个人都读一读，会让你重新审视自己和这个世界。',
    likes: [MOCK_USERS[0], MOCK_USERS[3], MOCK_USERS[4]],
    comments: [{id: 'c4', userId: 'u4', userName: '刘洋', content: '已购，准备看！'}],
    createdAt: Date.now() - 1000 * 60 * 30},
  {id: 'p3', user: MOCK_USERS[2], type: 'image', content: '今日午饭', images: [PHOTOS[1], PHOTOS[2]],
    likes: [MOCK_USERS[5]], comments: [], createdAt: Date.now() - 1000 * 60 * 60},
  {id: 'p4', user: MOCK_USERS[3], type: 'video', content: '孩子第一次走路，太感动了 😭',
    videoThumb: 'https://picsum.photos/seed/v1/400/300',
    likes: [MOCK_USERS[0], MOCK_USERS[1], MOCK_USERS[2], MOCK_USERS[4]],
    comments: [
      {id: 'c5', userId: 'u1', userName: '张伟', content: '恭喜恭喜！'},
      {id: 'c6', userId: 'u5', userName: '陈静', content: '太可爱了！'},
    ], createdAt: Date.now() - 1000 * 60 * 90},
  {id: 'p5', user: MOCK_USERS[4], type: 'image', content: '三亚三日游',
    images: [PHOTOS[3], PHOTOS[4], PHOTOS[5]], location: '三亚市',
    likes: [MOCK_USERS[1]], comments: [], createdAt: Date.now() - 1000 * 60 * 120},
  {id: 'p6', user: MOCK_USERS[5], type: 'text', content: '今天加班到11点，好累……',
    likes: [], comments: [{id: 'c7', userId: 'u2', userName: '李娜', content: '辛苦了，早点休息'}],
    createdAt: Date.now() - 1000 * 60 * 180},
  {id: 'p7', user: MOCK_USERS[0], type: 'image', content: '春天来了🌸',
    images: [PHOTOS[0], PHOTOS[1], PHOTOS[2], PHOTOS[3]],
    likes: [MOCK_USERS[2], MOCK_USERS[3]], comments: [], createdAt: Date.now() - 1000 * 60 * 240},
  {id: 'p8', user: MOCK_USERS[1], type: 'video', content: '分享一个有趣的舞蹈视频',
    videoThumb: 'https://picsum.photos/seed/v2/400/300',
    likes: [MOCK_USERS[0]], comments: [], createdAt: Date.now() - 1000 * 60 * 300},
  {id: 'p9', user: MOCK_USERS[2], type: 'image', content: '毕业季留念 📷',
    images: [PHOTOS[0], PHOTOS[1], PHOTOS[2], PHOTOS[3], PHOTOS[4], PHOTOS[5]],
    likes: [MOCK_USERS[0], MOCK_USERS[1], MOCK_USERS[3], MOCK_USERS[4], MOCK_USERS[5]],
    comments: [
      {id: 'c8', userId: 'u1', userName: '张伟', content: '青春永驻！'},
      {id: 'c9', userId: 'u4', userName: '刘洋', content: '好怀念啊'},
    ], createdAt: Date.now() - 1000 * 60 * 360},
  {id: 'p10', user: MOCK_USERS[3], type: 'image', content: '北京两日游全记录', images: PHOTOS, location: '北京市',
    likes: [MOCK_USERS[0], MOCK_USERS[2]],
    comments: [{id: 'c10', userId: 'u5', userName: '陈静', content: '下次带我去！'}],
    createdAt: Date.now() - 1000 * 60 * 480},
  {id: 'p11', user: MOCK_USERS[4], type: 'text', content: '每天坚持跑步第30天，身体状态好了很多，推荐大家都动起来！',
    likes: [MOCK_USERS[5]], comments: [], createdAt: Date.now() - 1000 * 60 * 600},
  {id: 'p12', user: MOCK_USERS[5], type: 'image', content: '新买的多肉🌵', images: [PHOTOS[2]],
    likes: [MOCK_USERS[1], MOCK_USERS[3]],
    comments: [{id: 'c11', userId: 'u2', userName: '李娜', content: '好可爱！'}],
    createdAt: Date.now() - 1000 * 60 * 720},
  {id: 'p13', user: MOCK_USERS[0], type: 'video', content: '公司年会表演，有点紧张哈哈',
    videoThumb: 'https://picsum.photos/seed/v3/400/300',
    likes: [MOCK_USERS[1], MOCK_USERS[2], MOCK_USERS[4]], comments: [],
    createdAt: Date.now() - 1000 * 60 * 840},
  {id: 'p14', user: MOCK_USERS[1], type: 'image', content: '晚霞真美', images: [PHOTOS[6], PHOTOS[7]],
    likes: [], comments: [], createdAt: Date.now() - 1000 * 60 * 960},
  {id: 'p15', user: MOCK_USERS[2], type: 'text', content: '下午茶时光 ☕',
    likes: [MOCK_USERS[0]],
    comments: [{id: 'c12', userId: 'u1', userName: '张伟', content: '叫我啊！'}],
    createdAt: Date.now() - 1000 * 60 * 1080},
  {id: 'p16', user: MOCK_USERS[3], type: 'image', content: '朋友聚会',
    images: [PHOTOS[0], PHOTOS[3], PHOTOS[6]],
    likes: [MOCK_USERS[4], MOCK_USERS[5]], comments: [], createdAt: Date.now() - 1000 * 60 * 1200},
  {id: 'p17', user: MOCK_USERS[4], type: 'image', content: '家里新装修完工了！',
    images: [PHOTOS[1], PHOTOS[4], PHOTOS[7], PHOTOS[8]],
    likes: [MOCK_USERS[0], MOCK_USERS[1], MOCK_USERS[2]],
    comments: [
      {id: 'c13', userId: 'u1', userName: '张伟', content: '太漂亮了！'},
      {id: 'c14', userId: 'u3', userName: '王芳', content: '设计师是谁？'},
    ], createdAt: Date.now() - 1000 * 60 * 1320},
  {id: 'p18', user: MOCK_USERS[5], type: 'video', content: '宠物日常，它今天心情很好',
    videoThumb: 'https://picsum.photos/seed/v4/400/300',
    likes: [MOCK_USERS[0], MOCK_USERS[2], MOCK_USERS[3]], comments: [],
    createdAt: Date.now() - 1000 * 60 * 1440},
  {id: 'p19', user: MOCK_USERS[0], type: 'image', content: '六月的风景',
    images: [PHOTOS[2], PHOTOS[5], PHOTOS[8], PHOTOS[1], PHOTOS[4], PHOTOS[7]],
    likes: [], comments: [], createdAt: Date.now() - 1000 * 60 * 1560},
  {id: 'p20', user: MOCK_USERS[1], type: 'text',
    content: '工作了五年，今天正式提交了辞职信。感谢这五年的成长，感谢遇到的每一个人。新的征程，加油！💪',
    likes: [MOCK_USERS[0], MOCK_USERS[2], MOCK_USERS[3], MOCK_USERS[4], MOCK_USERS[5]],
    comments: [
      {id: 'c15', userId: 'u3', userName: '王芳', content: '加油！期待你的新故事'},
      {id: 'c16', userId: 'u4', userName: '刘洋', content: '新的开始，一切都会好的！'},
    ], createdAt: Date.now() - 1000 * 60 * 1680},
];
